name: 'Configure Buildkit'
description: 'Configures the remote buildkit host using given credentials'
inputs:
  openvpn-config:  # id of input
    description: 'Content of an .ovpn configuration containing certificate to connect'
    required: true
  buildkit-ca-cert:
    description: 'CA Certificate configured with Buildkit'
    required: true
  buildkit-cert:
    description: 'Client certificate configured with Buildkit'
    required: true
  buildkit-cert-key:
    description: 'Private key for the client certificate configured with Buildkit'
    required: true
  buildkit-ip:
    description: 'Private IP address of the Buildkit daemon'
    required: true
  builder-name:
    description: 'Name of the Docker buildx builder'
    required: false
    default: 'remote-buildkit-host'
  wait-for-vpn-sleep:
    description: 'How long to sleep to wait for the VPN connection. In seconds'
    required: false
    default: '10s'

runs:
  using: "composite"
  steps:
      - name: Install OpenVPN
        shell: bash
        run: |
          sudo apt-get --assume-yes --no-install-recommends install openvpn          

      - name: Setup VPN config
        shell: bash
        run: |
          mkdir tmp
          echo "${{ inputs.openvpn-config }}" > ./tmp/config.ovpn
          echo "${{ inputs.buildkit-ca-cert }}" > ./tmp/ca.pem
          echo "${{ inputs.buildkit-cert }}" > ./tmp/cert.pem
          echo "${{ inputs.buildkit-cert-key }}" > ./tmp/key.pem

      - name: Connect VPN
        shell: bash
        run: sudo openvpn --config "./tmp/config.ovpn" --daemon

      - name: Waiting for a VPN connection
        shell: bash
        run: sleep ${{ inputs.wait-for-vpn-sleep }}

      - name: Setup Docker Builder
        shell: bash
        run: docker buildx create --name ${{ inputs.builder-name }} --driver-opt cacert=${PWD}/tmp/ca.pem,cert=${PWD}/tmp/cert.pem,key=${PWD}/tmp/key.pem,servername=127.0.0.1 --driver remote tcp://${{ inputs.buildkit-ip }}:8082

